# universal = Studio.create!(name: 'Universal Studios', location: 'Hollywood')
# ark = universal.movies.create!(title: 'Raiders of the Lost Ark', creation_year: 1981, genre: 'Action/Adventure')
# shrek = universal.movies.create!(title: 'Shrek', creation_year: 2000, genre: 'Comedy')

studio1 = Studio.create!(name: 'MGM', location: 'California')
movie1 = studio1.movies.create!(title: 'movie1', creation_year: 1994, genre: "Horror")
kevin = Actor.create!(name: 'Kevin', age: 24)
micha = Actor.create!(name: 'Micha', age: 27)
amwake = Actor.create!(name: 'Amwake', age: 33)
MovieActor.create!(movie_id: movie1.id, actor_id: kevin.id)
MovieActor.create!(movie_id: movie1.id, actor_id: micha.id)
MovieActor.create!(movie_id: movie1.id, actor_id: amwake.id)
